//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace VEM.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using VEM.Model;
    
    public partial class VemContainer : DbContext
    {
        public VemContainer()
            : base("name=VemContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MachineModel> MachineModelSet { get; set; }
        public virtual DbSet<City> CitySet { get; set; }
        public virtual DbSet<District> DistrictSet { get; set; }
        public virtual DbSet<UserRole> UserRoleSet { get; set; }
        public virtual DbSet<Role> RoleSet { get; set; }
        public virtual DbSet<Privilege> PrivilegeSet { get; set; }
        public virtual DbSet<Menu> MenuSet { get; set; }
        public virtual DbSet<Button> ButtonSet { get; set; }
        public virtual DbSet<Commod> CommodSet { get; set; }
        public virtual DbSet<SalesHistory> SalesHistorySet { get; set; }
        public virtual DbSet<ContainerRoad> ContainerRoadSet { get; set; }
        public virtual DbSet<Icon> IconSet { get; set; }
        public virtual DbSet<Machine> MachineSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
        public virtual DbSet<PayRecord> PayRecordSet { get; set; }
        public virtual DbSet<Coupon> CouponSet { get; set; }
        public virtual DbSet<MemberCoupon> MemberCouponSet { get; set; }
        public virtual DbSet<ShipmentStatusRecord> ShipmentStatusRecordSet { get; set; }
        public virtual DbSet<MachineTem> MachineTemSet { get; set; }
        public virtual DbSet<Fault> FaultSet { get; set; }
        public virtual DbSet<BrowserPrivilege> BrowserPrivilegeSet { get; set; }
    }
}
