//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    { 
        public City()
        {
            this.District = new HashSet<District>();
            this.Machine = new HashSet<Machine>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<District> District { get; set; }
        public virtual ICollection<Machine> Machine { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
