//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    { 
        public Machine()
        {
            this.ContainerRoad = new HashSet<ContainerRoad>();
            this.SalesHistory = new HashSet<SalesHistory>();
            this.ShipmentStatusRecord = new HashSet<ShipmentStatusRecord>();
            this.Error = new HashSet<Fault>();
        }
    
        public string Address { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string MachineCode { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public string SoftwareId { get; set; }
        public string HardwareId { get; set; }
        public int Id { get; set; }
        public Nullable<double> HighRefriTem { get; set; }
        public Nullable<double> LowRefriTem { get; set; }
        public Nullable<bool> RentOrSell { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual MachineModel MachineModel { get; set; }
        public virtual ICollection<ContainerRoad> ContainerRoad { get; set; }
        public virtual ICollection<SalesHistory> SalesHistory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ShipmentStatusRecord> ShipmentStatusRecord { get; set; }
        public virtual MachineTem MachineTem { get; set; }
        public virtual ICollection<Fault> Error { get; set; }
    }
}
