//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member : Person
    { 
        public Member()
        {
            this.PayRecord = new HashSet<PayRecord>();
            this.MemberCoupon = new HashSet<MemberCoupon>();
        }
    
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreateUserID { get; set; }
    
        public virtual ICollection<PayRecord> PayRecord { get; set; }
        public virtual ICollection<MemberCoupon> MemberCoupon { get; set; }
    }
}
