//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    { 
        public Menu()
        {
            this.Button = new HashSet<Button>();
        }
    
        public int Id { get; set; }
        public string MenuNo { get; set; }
        public string MenuParentNo { get; set; }
        public string MenuUrl { get; set; }
        public string MenuName { get; set; }
        public int MenuOrder { get; set; }
        public bool IsVisible { get; set; }
        public bool IsLeaf { get; set; }
        public string MenuPic { get; set; }
    
        public virtual ICollection<Button> Button { get; set; }
    }
}
