//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : Person
    { 
        public User()
        {
            this.UserRole = new HashSet<UserRole>();
            this.Machine = new HashSet<Machine>();
        }
    
        public string CompanyName { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifyUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<UserRole> UserRole { get; set; }
        public virtual ICollection<Machine> Machine { get; set; }
        public virtual City City { get; set; }
        public virtual District District { get; set; }
    }
}
